type: ACTION
language: PYTHON_3
name: Device Healthcheck
description: Run a health check of the device(s)
file: script.py
static-params: []
dynamic-params:
  - name: DeviceID
    description: The ID of the device to reload
    required: true
    hidden: false